# Generated by Django 5.1 on 2024-08-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropNutrientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, unique=True)),
                ('nitrogen_needed', models.FloatField(help_text='Total nitrogen required in kg/ha')),
                ('phosphorus_needed', models.FloatField(help_text='Total phosphorus required in kg/ha')),
                ('potassium_needed', models.FloatField(help_text='Total potassium required in kg/ha')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nitrogen_content', models.FloatField(help_text='Percentage of nitrogen content')),
                ('phosphorus_content', models.FloatField(help_text='Percentage of phosphorus content')),
                ('potassium_content', models.FloatField(help_text='Percentage of potassium content')),
            ],
        ),
    ]
