# Generated by Django 5.1 on 2024-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('crop_type', models.CharField(blank=True, max_length=255, null=True)),
                ('varieties', models.JSONField(blank=True, null=True)),
                ('techniques_used', models.JSONField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('rainfall', models.CharField(blank=True, max_length=50, null=True)),
                ('soil_type', models.JSONField(blank=True, null=True)),
                ('major_producers', models.JSONField(blank=True, null=True)),
                ('highest_producer', models.CharField(blank=True, max_length=255, null=True)),
                ('highest_per_hectare_yield', models.CharField(blank=True, max_length=255, null=True)),
                ('research_centre', models.JSONField(blank=True, null=True)),
                ('highest_producing_country', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
